### ISSUE TITLE
Does torch-cam still support 3D resnet model?

### ISSUE THREAD

**Issue by RogerLiu-Yuxuan** [frgfm/torch-cam#207]
I noticed that from the version update, your repo right now can suppot 3d model. Is it still supported? I tested the repo with a standard resnet-50 3d model. It through me this error information:

```
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yliu3342/code/Users/yliu334/amdprojectv2/class_activation_map.py", line 97, in <module>
    extractor = SmoothGradCAMpp(model)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torchcam/methods/gradient.py", line 239, in __init__
    super().__init__(model, target_layer, input_shape, **kwargs)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torchcam/methods/gradient.py", line 34, in __init__
    super().__init__(model, target_layer, input_shape, **kwargs)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torchcam/methods/core.py", line 53, in __init__
    target_name = locate_candidate_layer(model, input_shape)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torchcam/methods/_utils.py", line 43, in locate_candidate_layer
    _ = mod(torch.zeros((1, *input_shape), device=next(mod.parameters()).data.device))
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yliu3342/code/Users/yliu334/amdprojectv2/lib/models/resnet2p1d.py", line 246, in forward
    x = self.bn1_s(x)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 135, in forward
    self._check_input_dim(input)
  File "/anaconda/envs/py310_amd/lib/python3.10/site-packages/torch/nn/modules/batchnorm.py", line 513, in _check_input_dim
    raise ValueError("expected 5D input (got {}D input)".format(input.dim()))
ValueError: expected 5D input (got 4D input)
```

**Comment by frgfm** [comment]
Hi @RogerLiu-Yuxuan :wave:

Thanks for reporting this! Yes, this behaviour is expected and easily fixable:
- when you aren't specifying the `input_shape` argument when instantiating your CAM extractor, it default to (3, 224, 224).
- so in your case, I'm quite confident you only need to specify something like `input_shape=(3, 10, 224, 224)` for instance 

That should do it :smile: Let me know where this gets you!
Cheers :v:

**Comment by RogerLiu-Yuxuan** [comment]
Thanks for your reply!

Your suggestion works!

**Comment by frgfm** [comment]
Glad it helped :grin:
